apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: test
  name: test
  namespace: podpreset-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        imagePullPolicy: IfNotPresent
        args:
        - sleep
        - infinity
        resources:
          limits:
            memory: 70Mi
            cpu: 100m
          requests:
            cpu: 100m
            memory: 70Mi
